# Generated by Django 4.1.4 on 2023-01-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Pending', 'Pending')], default=False, max_length=7),
        ),
    ]
